{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from acp_python.client.session import AllowAllPolicy\n",
    "from acp_python.client.session import InMemorySessionStore\n",
    "from acp_python.client import AcpClient"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def message_handler(msg, client):\n",
    "    print(f\"Received message from {client.actor_id}: {msg.data}\")\n",
    "\n",
    "client_1 = AcpClient(\n",
    "    \"test-1\", \"\", InMemorySessionStore(), server_url=\"nats://137.66.48.8:4222\"\n",
    ")\n",
    "client_2 = AcpClient(\n",
    "    \"test-2\", \"\", InMemorySessionStore(), server_url=\"nats://137.66.48.8:4222\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<acp_python.client.client.AcpClient at 0x10706c910>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "nats: encountered error\n",
      "nats.errors.UnexpectedEOF: nats: unexpected EOF\n",
      "nats: encountered error\n",
      "nats.errors.UnexpectedEOF: nats: unexpected EOF\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n",
      "nats: encountered error\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1466, in _attempt_reconnect\n",
      "    await self._process_connect_init()\n",
      "  File \"/Users/tonyfrancis/workspace/acp-python/.venv/lib/python3.13/site-packages/nats/aio/client.py\", line 1940, in _process_connect_init\n",
      "    raise errors.Error(\n",
      "        \"nats: empty response from server when expecting INFO message\"\n",
      "    )\n",
      "nats.errors.Error: nats: empty response from server when expecting INFO message\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "\n",
    "await client_1.start()\n",
    "await client_2.start()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from nats.aio.client import Client as NatsClient"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "client_1._nc."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
